/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f7f9fb", 
        "primary-container": "#0056b3", 
        "on-surface": "#191c1e", 
        "inverse-surface": "#2d3133", 
        "on-error-container": "#93000a", 
        "tertiary-container": "#983c00", 
        "secondary-fixed-dim": "#b9c7df", 
        "tertiary-fixed": "#ffdbcc", 
        "inverse-on-surface": "#eff1f3", 
        "on-primary-fixed": "#001a40", 
        "surface-container-low": "#f2f4f6", 
        "on-secondary-fixed-variant": "#3a485b", 
        "secondary-container": "#d5e3fc", 
        "on-secondary-fixed": "#0d1c2e", 
        "surface-tint": "#115cb9", 
        "surface-container-lowest": "#ffffff", 
        "inverse-primary": "#acc7ff", 
        "on-tertiary": "#ffffff", 
        "on-error": "#ffffff", 
        primary: "#003f87", 
        "on-tertiary-fixed": "#351000", 
        "on-primary-container": "#bbd0ff", 
        "error-container": "#ffdad6", 
        tertiary: "#722b00", 
        outline: "#727784", 
        "on-surface-variant": "#424752", 
        "on-primary": "#ffffff", 
        "on-primary-fixed-variant": "#004491", 
        "on-secondary": "#ffffff", 
        "surface-container-highest": "#e0e3e5", 
        "secondary-fixed": "#d5e3fc", 
        "on-background": "#191c1e", 
        "on-secondary-container": "#57657a", 
        "primary-fixed": "#d7e2ff", 
        "surface-variant": "#e0e3e5", 
        "surface-container-high": "#e6e8ea", 
        secondary: "#515f74", 
        error: "#ba1a1a", 
        "on-tertiary-container": "#ffc2a7", 
        "primary-fixed-dim": "#acc7ff", 
        "outline-variant": "#c2c6d4", 
        "surface-container": "#eceef0", 
        "surface-dim": "#d8dadc", 
        "tertiary-fixed-dim": "#ffb694", 
        background: "#f7f9fb", 
        "surface-bright": "#f7f9fb", 
        "on-tertiary-fixed-variant": "#7b2f00"
      },
      borderRadius: {
        DEFAULT: "0.25rem", 
        lg: "0.5rem", 
        xl: "0.75rem", 
        full: "9999px"
      },
      spacing: {
        "grid-gutter": "12px", 
        "row-height-standard": "44px", 
        "row-height-dense": "32px", 
        unit: "4px", 
        "container-padding": "24px"
      },
      fontFamily: {
        "headline-md": ["Inter"], 
        "body-md": ["Inter"], 
        "headline-lg": ["Inter"], 
        "body-sm": ["Inter"], 
        "label-caps": ["Inter"], 
        "code-mono": ["monospace"],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['monospace'],
      },
      fontSize: {
        "headline-md": ["18px", {lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600"}], 
        "body-md": ["14px", {lineHeight: "20px", fontWeight: "400"}], 
        "headline-lg": ["24px", {lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600"}], 
        "body-sm": ["13px", {lineHeight: "18px", fontWeight: "400"}], 
        "label-caps": ["11px", {lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700"}], 
        "code-mono": ["12px", {lineHeight: "16px", fontWeight: "400"}]
      }
    },
  },
  plugins: [],
}
